### PR TITLE
[glib2] Update to version 2.78.4. JB#61330

### PR DESCRIPTION
**Pull request by mlehtima**
Requires integration of https://github.com/sailfishos/pcre2

### CODE REVIEW

**Review by pvuorela — APPROVED** [review]

**Comment by attah** [comment]
Please consider sneaking in a `BuildRequires: ccache`

**Comment by pvuorela** [comment]
> Please consider sneaking in a `BuildRequires: ccache`

Why?

**Comment by attah** [comment]
Because it is seems to be the case; i.e. wouldn't build with a clean-ish sfdk for me.
Other environments seems to have it somewhat by default, or left over since a previous package build, like i had: https://github.com/sailfishos/glib-networking/pull/2#discussion_r1440295724

**Comment by pvuorela** [comment]
> Because it is seems to be the case; i.e. wouldn't build with a clean-ish sfdk for me.

I don't think there's anything really here depending on it. I recall some meson related ccache detection problem leading to failures, but sprinkling the ccache dependency around would feel like papering over it. Should work if it's manually installed, I'd assume.

**Comment by attah** [comment]
You seem to be correct in that meson detects e.g.
``C++ compiler for the host machine: ccache c++ (gcc 8.3.0 "aarch64-meego-linux-gnu-c++ (Linaro GCC 8.2-2018.08~dev) 8.3.0 20190222 (Sailfish OS gcc 8.3.0-7)")

...but then ccache isn't actually available.
And indeed it seems optional: https://mesonbuild.com/Feature-autodetection.html

**Comment by attah** [comment]
Newer meson seems to have a related improvement; but it didn't help.... and i still think we are surviving on that other packages have installed ccache before and/or it being generally available.

**Comment by mlehtima** [comment]
Probably would make sense to have ccache installed in sdk targets or tooling (which ever is correct place for it) by default.

**Comment by pvuorela** [comment]
> Probably would make sense to have ccache installed in sdk targets or tooling (which ever is correct place for it) by default.

Indeed if not fixing the real problem, this would be a nicely isolated workaround. One place instead of here and there.

For the bug itself, I'm not sure is it even a meson bug or something towards sb2.

**Comment by pvuorela** [comment]
Maybe everyone noticed, but for reference the ccache issue fixed there https://github.com/sailfishos/scratchbox2/pull/24

**Comment by pvuorela** [comment]
Still good

**Pull request merged**
